services:
  story-testnet-geth:
    image: story-testnet-geth:v0.9.2
    build:
      context: .
      dockerfile: Dockerfile.geth
    restart: unless-stopped
    container_name: story-testnet-geth
    volumes:
      - './geth/:/story-node/.story/geth/'
      - './jwtsecret:/story-node/.story/geth/iliad/geth/jwtsecret'
    expose:
      - 8551
    ports:
      - '8545:8545'
      - '8546:8546'
      - '30303:30303'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
  story-testnet-beacon:
    image: story-testnet-beacon:v0.9.11
    build:
      context: .
      dockerfile: Dockerfile.story
    restart: unless-stopped
    container_name: story-testnet-beacon
    volumes:
      - './story:/story-node/.story/story'
      - './jwtsecret:/story-node/geth/iliad/geth/jwtsecret'
    expose:
      - 8551
    ports:
      - '1317:1317'
      - '26657:26657'
      - '26656:26656'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
